### ISSUE TITLE
Jekyll site local build instructions

### ISSUE THREAD

**Issue by engn33r** [Zellic/Masamune#4]
The project includes the description:

> Masamune is a static site, built with [Jekyll](https://jekyllrb.com/), and hosted on [Github Pages](https://pages.github.com/).

But I don't see any Jekyll files in this repo nor build instructions to test the site locally. Are these files found in a different repo? If so, it may be better to add a comment stating as much and name this repo `Masamune-data` to clarify the website build files are not located in this repo.

**Comment by joswha** [comment]
Oops, copilot generated description, forgot about this 😅 . Will update. To build locally, just open `index.html` using a live server, eg. [this for VSCode](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer).
